sudo: required
dist: trusty

stages:
  - test
  - deploy

cache:
  directories:
    - $HOME/haxe

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  - haxe master.hxml -D containers=node -D targets=js,node,php,neko,cpp
  - haxe master.hxml -D containers=node-tcp,neko-mod -D targets=node -D container_only
  # - haxe master.hxml -D containers=php -D targets=node -D container_only # Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version.
  # - haxe master.hxml -D containers=neko-tools -D targets=node # does not support PATCH/PUT/DELETE
  # - haxe master.hxml -D containers=node -D targets=cpp # haxeshim not working with cpp yet
  # - haxe master.hxml -D containers=tcp -D targets=node -lib tink_tcp -lib tink_runloop

jobs:
  include:
    # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
    - stage: deploy
      language: haxe
      haxe: "3.4.7"
      os: linux
      script: skip
      after_success:
        - haxelib install travix
        - haxelib run travix install
        - haxelib run travix release
