sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
      
install:
  - npm install

script:
  - npm run haxe -- master.hxml -D containers=node -D targets=node,neko,cpp
  - npm run haxe -- master.hxml -D containers=php -D targets=node
  # - npm run haxe -- master.hxml -D containers=node -D targets=js # why DELETE on travix does not send the body?
  # - npm run haxe -- master.hxml -D containers=tcp -D targets=node -lib tink_tcp -lib tink_runloop
