sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install tink_runloop
  - haxelib install tink_tcp
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko -lib tink_tcp -lib tink_runloop
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix flash
  - haxelib run travix java -lib tink_tcp -lib tink_runloop
  - haxelib run travix cpp -lib tink_tcp -lib tink_runloop
  - haxelib run travix cs
  - haxelib run travix php
