sudo: required
dist: trusty

language: haxe

#os:
#  - linux
#  - osx
  
haxe:
  - "3.2.1"
  - development
#  
#matrix:
#  allow_failures:
#    - haxe: development
    
install:
  - haxelib install tink_runloop --always
  - haxelib install tink_tcp --always
  - haxelib install travix --always
  - haxelib run travix install

script:
  # Test servers
  - haxe master.hxml -D containers=node -D targets=node