sudo: required
dist: trusty

language: haxe

#os:
#  - linux
#  - osx
  
haxe:
  - "3.2.1"
#  - development
#  
#matrix:
#  allow_failures:
#    - haxe: development
    
install:
  - haxelib install tink_runloop
  - haxelib install tink_tcp
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix neko -D server=NekoToolsServer -D client=NekoClient
  - haxelib run travix neko -D server=PhpServer -D client=PhpClient
  - haxelib run travix neko -D server=NodeServer -D client=NodeClient
  - haxelib run travix neko -D server=NekoServer -D client=NekoClient
  - haxelib run travix neko -D server=JavaServer -D client=NekoClient
  - haxelib run travix neko -D server=CppServer -D client=NekoClient
  - haxelib run travix neko -D server=ModNekoServer -D client=NekoClient
